### PR TITLE
Fix #973 Make sure all resources are closed in RegistrationIntentService

### LINKED ISSUE #973: RegistrationIntentService leaks a closeable FileOutputStream
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: prebuilt
  * Firebase C++ SDK version: 8.11.0
  * Problematic Firebase Component: Messaging
  * Other Firebase Components in use: none
  * Platform you are using the C++ SDK on: Mac
  * Platform you are targeting: Android

### [REQUIRED] Please describe the issue here:

- enable strict mode
- shows that closeable is leaked here https://github.com/firebase/firebase-cpp-sdk/blob/v9.0.0/messaging/src/android/java/com/google/firebase/messaging/cpp/RegistrationIntentService.java#L63

```log
2022-05-26 10:43:36.813 9571-9584/? D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1877)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
        at sun.nio.ch.FileChannelImpl.finalize(FileChannelImpl.java:175)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:237)
        at sun.nio.ch.FileChannelImpl.<init>(FileChannelImpl.java:110)
        at sun.nio.ch.FileChannelImpl.open(FileChannelImpl.java:128)
        at java.io.FileOutputStream.getChannel(FileOutputStream.java:469)
        at com.google.firebase.messaging.cpp.RegistrationIntentService.writeTokenToInternalStorage(SourceFile:6)
        at com.google.firebase.messaging.cpp.RegistrationIntentService.onHandleIntent(SourceFile:3)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

#### Steps to reproduce:

- Android project using Firebase Messaging
- enable strict mode

```kotlin
StrictMode.setVmPolicy(StrictMode.VmPolicy.Builder()
                    .detectActivityLeaks()
                    .detectLeakedClosableObjects()
                    .penaltyLog()
                    .build())
```

- check logcat for `D/StrictMode` logs

100% reproduce.

Sample project that reproduces the bug:

- Use https://github.com/firebase/quickstart-android/tree/master/messaging
- go to file https://github.com/firebase/quickstart-android/blob/master/messaging/app/src/main/java/com/google/firebase/quickstart/fcm/EntryChoiceActivity.kt
- add code:
```kotlin
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        StrictMode.setVmPolicy(
            StrictMode.VmPolicy.Builder()
                .detectLeakedClosableObjects()
                .penaltyLog()
                .build()
        )
    }
```

### PR DESCRIPTION
**Pull request by chkuang-g**
Make sure all FileStream and FileLock are closed using AutoClose pattern.

Make sure all the resource are closed RegistrationIntentService using AutoClose and try-with-resources statement.
***

Using integration test workflow (pending)
***

### Type of Change
Place an `x` the applicable box:
- [ ] Bug fix. Add the issue # below if applicable.
- [ ] New feature. A non-breaking change which adds functionality.
- [X] Other, such as a build process or documentation change.
***

#### Notes
- Bug fixes and feature changes require an update to the `Release Notes` section of `release_build_files/readme.md`.
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIBUTING.md).
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we can discuss it together.

### CODE REVIEW

File: messaging/src/android/java/com/google/firebase/messaging/cpp/RegistrationIntentService.java [hunk 1]
```diff
@@ -66,31 +66,19 @@ public static void writeTokenToInternalStorage(Context context, String token) {
...
-      // Acquire lock. This prevents the C++ code from consuming and clearing the file while we
-      // append to it.
-      FileOutputStream lockFileStream = context.openFileOutput(MessageWriter.LOCK_FILE, 0);
-      lock = lockFileStream.getChannel().lock();
 
-      FileOutputStream outputStream =
-          context.openFileOutput(MessageWriter.STORAGE_FILE, Context.MODE_APPEND);
-      // We send both the buffer length and the buffer itself so that we can potentially process
-      // more than one event in the case where they get queued up.
+    try (FileOutputStream lockFileStream = context.openFileOutput(MessageWriter.LOCK_FILE, 0);
```
Comment (cynthiajoan) [inline messaging/src/android/java/com/google/firebase/messaging/cpp/RegistrationIntentService.java:70]: nit, put this in a new line

**Review by cynthiajoan — APPROVED** [review]

**Review by a-maurice — APPROVED** [review]
